spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/issueabroad1
    username: issueabroad1
    password: issueabroad1
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security.web: trace
    issueabroad.first: debug